# **TRABALHO INDIVIDUAL: consultas SQL em base de dados sobre filmes**

> ###### ATENÇÃO!
> ###### - Faça o upload do arquivo CSV no Colab;
> ###### - Ao lado, clique nos ícones de pasta e folha (com seta para cima) para começar a transferência.
> ###### - Clique no botão play ▶ em cada célula para executar uma após a outra.

> ### PRÉ-PROCESSAMENTO DA BASE DE DADOS

In [1]:
# Preparação do ambiente
# Use a biblioteca Pandas para carregar o CSV e o SQLite para consultas SQL.
import pandas as pd
import sqlite3

In [2]:
# Carrega a planilha em formato CSV e salva a base de dados com o nome "filmes"
filmes = pd.read_csv('/content/Highest Holywood Grossing Movies.csv')

In [3]:
# Exibe primeiras linhas da base de dados
filmes.head(5)

,Unnamed: 0,Title,Movie Info,Year,Distributor,Budget (in $),Domestic Opening (in $),Domestic Sales (in $),International Sales (in $),World Wide Sales (in $),Release Date,Genre,Running Time,License
0,0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-Dec-09,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
1,1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000,1941066100,2799439100,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022,20th Century Studios,December 14 2022 (EMEA APAC),134100226,684075767,1636174514,2320250281,24-Apr-19,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
3,3,Titanic,A seventeen-year-old aristocrat falls in love ...,1997,Paramount Pictures,200000000,28638131,674292608,1590450697,2264743305,19-Dec-97,"['Drama', 'Romance']",3 hr 14 min,PG-13
4,4,Star Wars: Episode VII - The Force Awakens,"As a new threat to the galaxy rises, Rey, a de...",2015,Walt Disney Studios Motion Pictures,245000000,247966675,936662225,1134647993,2071310218,16-Dec-15,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13

In [4]:
# Mostra informações resumidas da base de dados inicial
filmes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  1000 non-null   int64
 1   Title                       1000 non-null   object
 2   Movie Info                  1000 non-null   object
 3   Year                        1000 non-null   int64
 4   Distributor                 999 non-null    object
 5   Budget (in $)               1000 non-null   object
 6   Domestic Opening (in $)     1000 non-null   object
 7   Domestic Sales (in $)       1000 non-null   int64
 8   International Sales (in $)  1000 non-null   int64
 9   World Wide Sales (in $)     1000 non-null   int64
 10  Release Date                1000 non-null   object
 11  Genre                       1000 non-null   object
 12  Running Time                1000 non-null   object
 13  License                     943 non-null    object
dtypes: int64(5), object(9)
memory usage: 109.5+ KB

In [5]:
# Mostra todos os nomes das colunas da base de dados
filmes.columns

Index(['Unnamed: 0', 'Title', 'Movie Info', 'Year', 'Distributor',
       'Budget (in $)', 'Domestic Opening (in $)', 'Domestic Sales (in $)',
       'International Sales (in $)', 'World Wide Sales (in $)', 'Release Date',
       'Genre', 'Running Time', 'License'],
      dtype='object')

In [6]:
# Renomeia as colunas com nomes em PT-BR
filmes = filmes.rename(columns={
    'Title': 'Titulo',
    'Movie Info': 'Sinopse',
    'Year': 'Ano',
    'Distributor': 'Distribuidora',
    'Budget (in $)': 'Orcamento (US$)',
    'Domestic Opening (in $)': 'Abertura Domestica (US$)',
    'Domestic Sales (in $)': 'Vendas Domesticas (US$)',
    'International Sales (in $)': 'Vendas Internacionais (US$)',
    'World Wide Sales (in $)': 'Vendas Globais (US$)',
    'Release Date': 'Lancamento',
    'Genre': 'Genero',
    'Running Time': 'Duracao',
    'License': 'Licenca'
})

In [7]:
# Remove coluna 'Unnamed: 0' (elimina repetição da ordem numérica das linhas)
filmes = filmes.drop(columns=['Unnamed: 0'])

# Converte coluna 'Lancamento' para o formato datetime64 (data numérica)
filmes['Lancamento'] = pd.to_datetime(filmes['Lancamento'], format='%d-%b-%y')

# Formata a coluna de data para 'dia-mes-ano'
filmes['Lancamento'] = filmes['Lancamento'].dt.strftime('%d-%m-%Y')

In [8]:
# Salva o novo dataset
filmes.to_csv('filmes_modificado.csv', index=False)

print("Dataset modificado, datas convertidas, e foi salvo com sucesso!")

# Exibe primeiras linhas da base de dados modificada
filmes.head(5)

Dataset modificado, datas convertidas, e foi salvo com sucesso!

,Titulo,Sinopse,Ano,Distribuidora,Orcamento (US$),Abertura Domestica (US$),Vendas Domesticas (US$),Vendas Internacionais (US$),Vendas Globais (US$),Lancamento,Genero,Duracao,Licenca
0,Avatar,A paraplegic Marine dispatched to the moon Pan...,2009,Twentieth Century Fox,237000000,77025481,785221649,2138484377,2923706026,16-12-2009,"['Action', 'Adventure', 'Fantasy', 'Sci-Fi']",2 hr 42 min,PG-13
1,Avengers: Endgame,After the devastating events of Avengers: Infi...,2019,Walt Disney Studios Motion Pictures,356000000,357115007,858373000,1941066100,2799439100,24-04-2019,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
2,Avatar: The Way of Water,Jake Sully lives with his newfound family form...,2022,20th Century Studios,December 14 2022 (EMEA APAC),134100226,684075767,1636174514,2320250281,24-04-2019,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",3 hr 1 min,PG-13
3,Titanic,A seventeen-year-old aristocrat falls in love ...,1997,Paramount Pictures,200000000,28638131,674292608,1590450697,2264743305,19-12-1997,"['Drama', 'Romance']",3 hr 14 min,PG-13
4,Star Wars: Episode VII - The Force Awakens,"As a new threat to the galaxy rises, Rey, a de...",2015,Walt Disney Studios Motion Pictures,245000000,247966675,936662225,1134647993,2071310218,16-12-2015,"['Action', 'Adventure', 'Sci-Fi']",2 hr 18 min,PG-13

# PARTE II

> ### CONSULTAS SQL NA BASE DE DADOS MODIFICADA

In [9]:
# Conectar ao banco de dados SQLite
connect = sqlite3.connect(':memory:')
filmes.to_sql('filmes', connect, index=False, if_exists='replace')

1000

###### 1. Obtenha apenas os títulos dos filmes e seus orçamentos.

In [10]:
# Selecionar colunas específicas
query = "SELECT Titulo, `Orcamento (US$)` FROM filmes;"
results = pd.read_sql_query(query, connect)
results

                                         Titulo               Orcamento (US$)
0                                        Avatar                     237000000
1                             Avengers: Endgame                     356000000
2                      Avatar: The Way of Water  December 14 2022 (EMEA APAC)
3                                       Titanic                     200000000
4    Star Wars: Episode VII - The Force Awakens                     245000000
..                                          ...                           ...
995                          Sweet Home Alabama                      30000000
996                              Daddy's Home 2                      69000000
997                               Hacksaw Ridge                      40000000
998                                     Deja Vu                      75000000
999                                       M3GAN       December 28 2022 (EMEA)

[1000 rows x 2 columns]

###### 2. Liste todos os filmes lançados após o ano 2000, mostrando o título e o ano de lançamento.

In [11]:
# Filtrar resultados
query = "SELECT Titulo, Ano FROM filmes WHERE Ano > 2000;"
results = pd.read_sql_query(query, connect)
results

                                         Titulo   Ano
0                                        Avatar  2009
1                             Avengers: Endgame  2019
2                      Avatar: The Way of Water  2022
3    Star Wars: Episode VII - The Force Awakens  2015
4                        Avengers: Infinity War  2018
..                                          ...   ...
781                          Sweet Home Alabama  2002
782                              Daddy's Home 2  2017
783                               Hacksaw Ridge  2016
784                                     Deja Vu  2006
785                                       M3GAN  2022

[786 rows x 2 columns]

###### 3. Liste os títulos dos filmes ordenados pelas vendas globais em ordem crescente, mostrando os valores.

In [12]:
# Ordenar resultados
query = "SELECT Titulo, `Vendas Globais (US$)` FROM filmes ORDER BY `Vendas Globais (US$)`;"
results = pd.read_sql_query(query, connect)
results

                                         Titulo  Vendas Globais (US$)
0                                         M3GAN             179968873
1                                       Deja Vu             180557550
2                                 Hacksaw Ridge             180563636
3                                Daddy's Home 2             180613824
4                            Sweet Home Alabama             180622424
..                                          ...                   ...
995  Star Wars: Episode VII - The Force Awakens            2071310218
996                                     Titanic            2264743305
997                    Avatar: The Way of Water            2320250281
998                           Avengers: Endgame            2799439100
999                                      Avatar            2923706026

[1000 rows x 2 columns]

###### 4. Conte quantos filmes da distribuidora "Walt Disney Studios Motion Pictures" existem na base de dados.

In [13]:
# Contar registros
query = "SELECT COUNT(*) FROM filmes WHERE Distribuidora = 'Walt Disney Studios Motion Pictures';"
results = pd.read_sql_query(query, connect)
print("A distribuidora Walt Disney Studios Motion Pictures possui", results.iloc[0, 0], "filmes.")

A distribuidora Walt Disney Studios Motion Pictures possui 159 filmes.

###### 5. Calcule a média de vendas globais dos filmes lançados entre 1990 e 2000.

In [14]:
# Usar funções de agregação
query = "SELECT AVG(`Vendas Globais (US$)`) FROM filmes WHERE Ano BETWEEN 1990 AND 2000;"
results = pd.read_sql_query(query, connect)
media_vendas = format(results.iloc[0, 0], ',.2f')
print(f"A média de vendas dos filmes entre 1990 e 2000 é de US$ {media_vendas}")

A média de vendas dos filmes entre 1990 e 2000 é de US$ 326,914,920.76

######  6. Calcule o total de vendas globais de filmes por distribuidora.

In [15]:
# Agrupar resultados
query = "SELECT Distribuidora, SUM(`Vendas Globais (US$)`) AS Total_Vendas FROM filmes GROUP BY Distribuidora;"
results = pd.read_sql_query(query, connect)
results

                          Distribuidora  Total_Vendas
0                                  None     245179562
1                         $117,000,000      261989769
2                           $4,500,000      255745157
3                  20th Century Studios    2651776879
4                          AMC Theaters     197757387
..                                  ...           ...
67                   Universal Pictures   54630707804
68                     Vestron Pictures     214577242
69  Walt Disney Studios Motion Pictures   89495799187
70                         Warner Bros.   70385715926
71            Well Go USA Entertainment    3584271270

[72 rows x 2 columns]

###### 7. Liste as distribuidoras que têm mais de 50 filmes.

In [16]:
# Filtrar Dados Agrupados com cláusula HAVING
query = "SELECT Distribuidora, COUNT(*) AS Total_Filmes FROM filmes GROUP BY Distribuidora HAVING Total_Filmes > 50;"
results = pd.read_sql_query(query, connect)
results

                         Distribuidora  Total_Filmes
0                   Paramount Pictures            93
1    Sony Pictures Entertainment (SPE)           104
2                Twentieth Century Fox           123
3                   Universal Pictures           130
4  Walt Disney Studios Motion Pictures           159
5                         Warner Bros.           166

###### 8. Selecionar os filmes com maior venda doméstica e maior venda global, mostrando os valores.

In [17]:
# Selecionar o filme com maior venda doméstica
query = "SELECT Titulo, `Vendas Domesticas (US$)` FROM filmes WHERE `Vendas Domesticas (US$)` = (SELECT MAX(`Vendas Domesticas (US$)`) FROM filmes);"
results = pd.read_sql_query(query, connect)

# Formatar o valor das vendas com separadores de milhares
vendas_formatadas = format(results.iloc[0, 1], ',.2f')
print("O filme com maior venda doméstica é:", results.iloc[0, 0], "com US$", vendas_formatadas)

O filme com maior venda doméstica é: Star Wars: Episode VII - The Force Awakens com US$ 936,662,225.00

In [18]:
# Selecionar o filme com maior venda global
query = "SELECT Titulo, `Vendas Globais (US$)` FROM filmes WHERE `Vendas Globais (US$)` = (SELECT MAX(`Vendas Globais (US$)`) FROM filmes);"
results = pd.read_sql_query(query, connect)

# Formatar o valor das vendas com separadores de milhares
vendas_formatadas = format(results.iloc[0, 1], ',.2f')
print("O filme com maior venda global é:", results.iloc[0, 0], "com US$", vendas_formatadas)

O filme com maior venda global é: Avatar com US$ 2,923,706,026.00

###### Parabéns por chegar ao final deste notebook. Aproveite para salvar uma cópia no seu Google Drive (no menu superior, clicando em Arquivo/Salvar uma cópia no Drive). Bons estudos! 🤩